import React from "react";
import { ReactNavbar } from "overlay-navbar";
import logo from "../../../images/logo.png";
import {MdAccountCircle } from "react-icons/md";
import {MdSearch } from "react-icons/md";
import {MdAddShoppingCart } from "react-icons/md";

const options = {
  burgerColor:"black",
  burgerColorHover:"#228B22",
  navColor1:"#FFFAF0",
  navColor2:"#FF4500",
  navColor3:"#FF4500",
  navColor4:"#FF4500",
  logo,
  logoWidth:"15vmax",
  logoHoverSize:"15px",
  logoHoverColor:"#8B0000",
  logoTransition:0.7,
  logoAnimationTime:1.1,
  nav1FlexDirection:"row",
  nav2FlexDirection:"row",
  nav3FlexDirection:"row",
  nav4FlexDirection:"row",
  nav1alignItems:"center",
  nav2alignItems:"center",
  nav3alignItems:"center",
  nav4alignItems:"center",
  nav1justifyContent:"center",
  nav2justifyContent:"center",
  nav3justifyContent:"center",
  nav4justifyContent:"center",
  nav1Transition:0.4,	
  nav2Transition:0.8,
  nav3Transition:1.2,
  nav4Transition:1.6,
  link1Text:"Home",
  link2Text:"Products",
  link3Text:"Contact",
  link4Text:"About",
  link1Url:"/",
  link2Url:"/products",
  link3Url:"/contact",
  link4Url:"/about",
  link1Size:"1.7vmax",
  link2Size:"1.7vmax",	
  link3Size:"1.7vmax",
  link4Size:"1.7vmax",
  link1Family:"Times New Roman",
  link2Family:"Times New Roman",
  link3Family:"Times New Roman",
  link4Family:"Times New Roman",
  link1Color:"#FFFAF0",	
  link2Color:"#FFFAF0",	
  link3Color:"#FFFAF0",	
  link4Color:"#FFFAF0",	
  link1ColorHover:"DarkRed",	
  link2ColorHover:"DarkRed",	
  link3ColorHover:"DarkRed",	
  link4ColorHover:"DarkRed",
  link1Margin:"1vmax",	
  link2Margin:"1vmax",	
  link3Margin:"1vmax",	
  link4Margin:"1vmax",
  profileIconUrl: "/login", 
  profileIcon:true,
  profileIconColor: "#FFFAF0",
  ProfileIconElement: MdAccountCircle, 
  searchIcon:true,
  searchIconColor: "#FFFAF0",
  SearchIconElement:MdSearch,
  cartIcon:true,
  cartIconColor: "#FFFAF0",
  CartIconElement:MdAddShoppingCart,
  searchIconMargin:"1.5vmax",	
  cartIconMargin:"1.5vmax",
  profileIconMargin:"1.5vmax",	
  searchIconUrl:"/search",
  cartIconUrl:"/cart",	
  searchIconSize:"2.5vmax",	
  cartIconSize:"2.5vmax",
  profileIconSize:"2.5vmax",	
  searchIconColorHover:"DarkRed",	
  cartIconColorHover:"DarkRed",
  profileIconColorHover:"DarkRed",
  searchIconTransition:0.5,	
  cartIconTransition:0.5,
  profileIconTransition:0.5,
  searchIconAnimationTime:2,
  cartIconAnimationTime:2.5,
  profileIconAnimationTime:3,
};

const Header = () => {
  return <ReactNavbar {...options} />;
};

export default Header;